### PR TITLE
Add the VWF Dialogues Patch

### PR DESCRIPTION
**Pull request by ExE-Boss**
Since the original VWF Dialogues Patch which is available on SMW Central still hasn’t been made SA-1 compatible and the SA-1 compatible version is still xkas based and due to Dropbox killing the [SA-1 Converted Patches site](https://dl.dropboxusercontent.com/u/16203903/A/SA1/cpatches.html) is no longer available on the internet.

So I’ve decided to merge the SA-1 Converted version into the main patch and upload it here, modified to match the coding style of this repository (see #1).

### CODE REVIEW

**Comment by RPGHacker** [comment]
WOW, thanks a lot! That was probably quite some nasty work. As always, I'll need some time before merging the pull request, but feel free to submit an update on SMW Central already. :)

**Comment by ExE-Boss** [comment]
I’m currently experiencing a visual bug on SA-1 when using the choice selector in that the cursor doesn’t disappear when moved. I have yet to confirm if this bug also occurs when not using the SA-1.

**Comment by RPGHacker** [comment]
I actually remember that bug, though I thought someone had already fixed it at some point. Not sure if that's true, and if it is, not sure which version it was in. From what I remember, the bug occurs because the code that renders the cursors exceeds the time available for V-Blank or something like that.

**Comment by RPGHacker** [comment]
It seems the Readme is kinda broken in my browser (newest version of Firefox).

https://puu.sh/zYaYk/e63d717258.png

Note sure if this was already in the original released versions or if it were adjustments made in this pull request?

**Comment by ExE-Boss** [comment]
It works on my machine (also Firefox 59.0).

As a test, try https://getbootstrap.com/, https://ExE-Boss.tech and https://novaapi.net, as they all use the same base css as this.

vwf-readme

**Comment by RPGHacker** [comment]
I'm also on Firefox 59 (the 64-bit verson).

Those links seem to work fine for me (at least from what I can tell). That's certainly weird. Maybe I'm using something incorrectly? I'm directly opening readme.html in my browser. That's supposed to be the root file, right?

**Comment by RPGHacker** [comment]
On a slightly unrelated note, the patch also currently doesn't work for me, though it's literally been years since I've used it for the last time and I may just be applying my own patch incorrectly (too lazy to read through the whole Readme right now). Shouldn't just applying vwf_dialogues.asm work? From what I would assume, SRAM expansion wasn't applied (the SRM file is only 2 KB in size). Didn't the patch use to do that automatically at some point? (As I said, has literally been years since I used the patch)

**Comment by RPGHacker** [comment]
Firefox's debug console read the following when opening the readme:

`Laden fehlgeschlagen für das <script> mit der Quelle "https://static.doubleclick.net/instream/ad_status.js".`

(It basically says that it failed to load the script from the source at that URL)

**Comment by ExE-Boss** [comment]
Just remove the `integrity` and `crossorigin` attributes from the `<script>` and `<link>` elements: https://github.com/RPGHacker/SMW-Workspace/blob/f85b36f249de0a8e4362d09f64be90464abeb23a/patches/vwf_dialogues/readme/readme.html#L9-L13

Since we’re loading the files locally, they’re not needed anyway.

**Comment by RPGHacker** [comment]
That worked. I wonder, what were those for? And why did they fail? (I didn't edit any of the include files)

**Comment by ExE-Boss** [comment]
They’re [Subresource Integrity validation attributes](https://developer.mozilla.org/docs/Web/Security/Subresource_Integrity), they’re needed when loading third party scripts and CSS to ensure that a malicious third party didn’t alter them somehow.

**Comment by RPGHacker** [comment]
Ah, I see. Weird that they just failed like that. Maybe git did something weird with the files to mess with the checksum or something like that...

**Comment by ExE-Boss** [comment]
It’s probably [line ending conversion](https://help.github.com/articles/dealing-with-line-endings/), I always use just `LF`, but Windows uses `CR LF`, so that’s probably the culprit.

**Comment by RPGHacker** [comment]
Probably something like that. Didn't know git did that.

Also note on the patch itself: it seems to still work fine in an SA-1 ROM, but not in a regular ROM. Maybe some of SA-1 fixes broke the base version? Will take a closer look later, but for now I have to leave, unfortunately.

**Comment by ExE-Boss** [comment]
It worked on a regular ROM for me on [bsnes plus](https://github.com/devinacker/bsnes-plus) and [no$sns](http://problemkaputt.de/sns.htm).

**Comment by RPGHacker** [comment]
As I expected, the missing SRAM expansion was the culprit. This piece of code here

```
org $00FFD8|$800000		; SRAM expansion ($07 => 2^7 kb)
	db $07
```

Was removed from the patch, I'm not quite sure why. Since the default settings of the patch use SRAM as working memory and thus require SRAM expansion to work (because SMW's default SRAM size is only 2 kb), this broke the patch in non-SA-1 mode. Not sure why it worked in SA-1 mode, though. I'm assuming the SA-1 patch applies a SRAM expansion automatically? Anyways, I added this to the patch

```
; SRAM expansion ($07 => 2^7 kb = 128 kb)
if !patch_sram_expansion != 0
	org remap_rom($00FFD8)
		db $07
endif
```

And added this to the cfg file:
```
; Whether to automatically apply SRAM expansion
; (By default, only applies to non SA-1 ROMs and is required if you leave address defines on top unchanged)
!patch_sram_expansion	= not(!use_sa1_mapping)
```

It's now working in both SA-1 mode and non-SA-1 mode again.
If it's okay with you, I will submit the updated version of this patch to SMW Central later (will first have to fix the Readme a bit).

**Comment by RPGHacker** [comment]
Submitted the updated patch to SMW over here:

https://www.smwcentral.net/?p=section&a=details&id=17404

**Pull request merged**
