### PR TITLE
VWF Dialogues Patch – Version 1.3

### LINKED ISSUE #6: (VWF patch) Implement some fixes/improvements mentioned in removal log by Blind Devil
So the recent submission of the VWF patch was rejected and Blind Devil did some unexpectedly elaborate testing on it.

https://smwc.me/1468216

I agree with most of the errors and suggestions listed there. The only two I don't agree with:

* Fixing the 16-bit stuff. I don't think it's worth it. Instead, I would just get rid of 16-bit mode entirely. I don't think anyone uses it and there probably wasn't a point in adding it in the first place.
* Merging the .cfg file with the .asm file. Not having to look into the .asm file to change stuff was the entire point of having a .cfg file. Opening and/or changing the .asm should only be required by advanced users.

All of the other suggestions sound reasonable and should be considered.

### PR DESCRIPTION
**Pull request by ExE-Boss**
This is my collection of fixes for version 1.3 of the VWF Dialogues Patch, also I would prefer if this was merged using a merge commit, rather than a squash and merge, like in the [asar](https://github.com/RPGHacker/asar) repository, as it helps to see what each change did.

### Important (https://smwc.me/1468216):
- [x] Fix the options cursor (yes, [this does consist of just one line of code](https://github.com/RPGHacker/SMW-Workspace/commit/1c6d7bd6086e8c3299c543afde0e6d5d1af85edf#diff-4da1ac633344d649ef3c90e72a723fce))
- [x] Correct the typo in `vwfmessagepointers.asm`
- [x] Fix the `$F4` escape code when trying to display character `$FF`.
- [ ] Fix the display clearing issue (there’s a Flash of `0`s when the GFX gets restored, but the tilemap still consists of the old data when using translucency or something).
    
    Could potentially be fixed by blanking tile `$FC` in the VWF GFX (since it might have been overwritten by a character tile) and setting the tilemap to `$FC`, then restoring the GFX and then restoring the tilemap, as SMW uses tile `$FC` for the transparent tile, whereas the VWF Dialogues Patch uses `$00` for the transparent tile.

### Readme:
- [x] `!bitmode` can be `!8` or `!16`
- [x] `!hijackbox` can be `!true` or `!false`
- [x] Notify that setup teleport currently doesn’t support LM’s expanded secondary entrances and that there are currently issues with midway point teleportation.
- [x] `$F3` gets reset by `$ED`
- [x] Add compatibility warnings with other patches
- [x] Add the 16-Bit mode deprecation warning
- [x] Document newly discovered issues (https://smwc.me/1468216)
- [x] Add more planned features
- [x] Proofread the whole thing to correct typos and ensure that all code is contained inside of `<code>` blocks.

---

Fixes #6

### CODE REVIEW

**Comment by RPGHacker** [comment]
Nice work already, you're fast! 👍
A minor suggestion I have: I would still leave the version number at 1.2 (and merge the changes), since technically the last version was rejected and thus never officially "released", which might get confusing for people looking through the version history. That's only a minor thing, though.

**Comment by ExE-Boss** [comment]
Or call it Version 1.2.1.

**Comment by ExE-Boss** [comment]
In the meantime, you could go look at merging and publishing #5, as that’s already completed.

**Comment by RPGHacker** [comment]
Yep, I'm planning to get there eventually. :)
Just have very little free time and like a bazillion things on my to do list, which is why it usually takes me an infinitillion years to merge larger pull request. Haven't forgotten about it, though.

**Comment by randomdude999** [comment]
Alright, I'll proofread it.

**Comment by randomdude999** [comment]
* If you expand Video 2 and then Video 1, then video 2 will jump to the right. I think Video 2 should be in the right side always.
* \>videos recorded using ZSNES (or something with equally crappy spc emulation)
please no
* Introduction, paragraph 2: "The cost of this is a way harder usage" - this sounds a bit odd, I'd replace it with "The cost of this is that it's way harder to use".
* Getting Started, paragraph 1: "vwfmessages1.asm" doesn't exist, there's only "vwfmessages.asm", also the file list doesn't mention "vwf_dialogues.cfg" although the next line says to edit it. Also it doesn't mention "vwffontpointers.asm" or "vwfframes.asm". I think it should just say "all the ASM, BIN, TXT and CFG files". Actually, never mind that, the patch also needs "../shared to exist, so we should rephrase that part entirely.
* Section "Background graphics", right under first screenshot: "You only have to rules to follow" - i think you meant "You only have two rules to follow". Also I didn't really understand rule 2 of that one - are you referring to the first color being hard coded to transparency?
* Next paragraph: "Translhextion" - I think there are better editors now, and this one isn't even hosted in the tools section anymore
* Section "Frame graphics and palettes", 2nd to last paragraph: Says that the palettes are in vwf_dialogues.asm, but they are in vwfframes.asm instead.
* Section "Setting Up and Calling Dialogues", paragraph 2 and list items 1-2: The addresses in the code don't match up with the addresses in the screenshot, which might confuse new users.
* "Dialogue Headers", paragraph 3: you need to set Windows Calculator to Programmer to convert between bin, hex and dec, not Scientific. Also there's a typo in that sentence.
* "Dialogue Headers", code block 2: I'm not sure that `db %jjjj----` is valid (with jjjj being only 0s and 1s). I think it should be `db %jjjj0000`. Also in "Dialogue Texts", description of `$F3` and `$EF`.
* "Dialogue Headers", description of `m` flag: maybe it should mention SA-1 instead of FastROM.
* "Dialogue Headers", description of `kkkk`: "Third color of the palette set up with ppp in SNES RGB" - I don't quite understand what you mean by this.
* "Dialogue Texts", description of `$FF`: "and the text box will vanishing" -> "and the text box will vanish"
* "Dialogue Texts", description of `$FE`: "It does something else, to." -> "It does something else, too."
* "Dialogue Texts", description of `$F8`: The `$XX` is not formatted as code. Also in description of `$F7`, `$F5`, `$F4` (here you have an entire line of code in double-quotes instead of code), `$F3`, `$F2`, `$F1` (i think the define names and maths in quotes should use code formatting too), `$F0` (if you formatted the single characters referring to the code as code it would probably not look so much like a wall of text), the section "Bank Limits".
* "Dialogue Texts", description of `$F3`: The end of this sounds like the game would crash if you changed palette mid-word, I think it only causes the color to abruptly change for a single letter. We should mention that.
* "Dialogue Texts", description of `$F1`: It's low-high-bank, not low-middle-high
* "Dialogue Texts", description of `$F0`: massive wall of text: I think this should be split into multiple paragraphs. In the middle of it: "occures" -> "occurs"
* "Dialogue Texts", description of `$EF`: "occure" -> "occur"
* "Dialogue Texts", description of `$ED`: Should mention resetting the text palette too
* "Dialogues Without Freezing Sprites": SA-1 preview link ("Case in point.") is slightly lower than the sentence before it. That's because buttons automatically have some padding.
* Also, clicking on any section links scrolls slightly too far down so the title of the section is hidden behind the navigation bar.
* Also, the screenshots look like they are taken from Windows XP, maybe they should be updated.

also if it takes me 2 hours to read a readme then it should be called a manual

**Comment by RPGHacker** [comment]
Thanks, that's a very detailed list! Two hours, wow. I wonder how long it took me to write most of that back in the day, but it's over seven years since I've made it, so I don't remember anything, ahahaha.

> also if it takes me 2 hours to read a readme then it should be called a manual

Might be a good idea to also add a simple README.txt which points at the manual, while simultanously serving as the README for GitHub (I would keep it rather simple and not at a whole lot of special formatting - pretty much like what I did with the other readmes to my other patches).

**Comment by ExE-Boss** [comment]
> "Dialogue Headers", paragraph 3: you need to set Windows Calculator to Programmer to convert between bin, hex and dec, not Scientific.

Back in the Windows XP era, Windows Calculator only supported Basic and Scientific modes, with the functionality of the new Programmer mode being part of Scientific back then.

**Comment by randomdude999** [comment]
In that case, I believe it should still be updated, since almost no-one uses XP anymore. Maybe mention that on XP, you need to use Scientific while on modern windows you need to use Programmer.

**Comment by ExE-Boss** [comment]
> "Dialogue Headers", code block 2: I'm not sure that `db %jjjj----` is valid (with `jjjj` being only `0`s and `1`s). I think it should be `db %jjjj0000`. Also in "Dialogue Texts", description of `$F3` and `$EF`.

The `-` means that the bit is ignored.

**Comment by RPGHacker** [comment]
Yeah, that part confused me, too. But I guess people who don't write code might be confused by the ----, so it might not be a bad idea to mention that they should just put a 0 for - (I probably wouldn't outright replace the - by 0, since 0 can easily be confused for an O, which might lead to some confusion).

**Comment by randomdude999** [comment]
You forgot the `#` in the text command links in the table of contents, so the links are broken (they go to a nonexistent page).

**Comment by ExE-Boss** [comment]
@RPGHacker Do you think this PR can be merged in this state (and defer fixing the Flash of `0`s until version 1.4 or later)?

**Comment by RPGHacker** [comment]
Will try to review it later when I'm back home (if I can manage somehow). Or maybe on the weekend.

**Comment by RPGHacker** [comment]
I wonder: Was there a specific reason to change all the varram defines into hex numbers? Is that an Asar optimization or something like that?

**Comment by RPGHacker** [comment]
I agree that it makes more sense when working with addresses in general, but not when using byte sizes in decimal. The decimal numbers made it easier to calculate the correct offset by looking at the number of bytes in the comments. I think that was one of the main reasons I used decimal literals back then.

**Comment by ExE-Boss** [comment]
I changed it to hex so that when I’m using my debugger to watch the RAM, I can calculate the location a lot faster in my head (eg. `$702000+$10E` is a lot easier to process than `$702000+270`)

**Comment by RPGHacker** [comment]
I'm not quite sure, what it is, but unfortunately something in this pull request seems to have broken the patch. I've tested multiple emulators. When I start an entirely new save file (in either SA-1 or non-SA-1 version), then the first dialogue (in the intro level) play out fine, but once I enter Yoshi's House and jump against the message block, the message never disappears and keeps playing the letter sound effect. The same happens with the first message block in level 105 and, presumeably, other message blocks. I did change a few things about the patch myself today, but I downloaded the repository from just after merging this pull request to confirm that it was already broken at that point in time.

**Comment by RPGHacker** [comment]
Tried different versions and determined that 4ed5858c0050b8418a85e064607e63d433abfb2c was the commit which broke it. Not quite sure what change exactly, but if I had to guess, I would assume it has something to do with `!enddialog`. I'm not quite sure what it does, and it seems to be used in a few weird and unexpected places.

**Comment by RPGHacker** [comment]
I think these
```
lda #$01
sta !enddialog
```
weren't added in the correct place. That's in the routine which calculates the width of the next word. Doesn't really make sense to "end" the dialogue in there, that should be done in the main processing somewhere. Not sure if this actually leads to the problems I observed, though, it doesn't quite seem to match up (if anything, I would expect dialogs to end prematurely).

**Pull request merged**
